StoryDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import story.urls

urlpatterns = [
    url(r'^$', 'story.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^story/', include(story.urls, namespace="story")),
]

story/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^createnode/(?P<id>\d+)$', views.createnode, name='createnode'),
    url(r'^createstory$', views.createstory, name='createstory'),
    url(r'^node/(?P<id>\d+)$', views.node, name='node'),
    url(r'^story/(?P<id>\d+)$', views.story, name='story'),
    url(r'^nodelist/(?P<parentid>\d+)/(?P<id>\d+)?$', views.nodelist, name='nodelist'),

    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
]

story/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Story(models.Model):
    title = models.CharField(max_length=256)
    created_by = models.ForeignKey(User)
    root = models.ForeignKey('StoryNode', related_name='+', null=True)

    def get_absolute_url(self):
        return reverse('story:story', kwargs={'id': self.id})


class StoryNode(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    parent = models.ForeignKey('StoryNode', null=True)
    story = models.ForeignKey(Story)
    stars = models.IntegerField(default=0)
    created_by = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('story:node', kwargs={'id': self.id})

story/forms.py
# coding: utf-8
from django import forms
from django.contrib.auth.models import User
from .models import Story, StoryNode


class RegisterForm(forms.ModelForm):
    username = forms.CharField(label=u'帐号')
    first_name = forms.CharField(label=u'昵称')
    password1 = forms.CharField(widget=forms.PasswordInput, label=u'密码')
    password2 = forms.CharField(widget=forms.PasswordInput, label=u'确认')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                u'输入密码不匹配',
                code='password_mismatch',
            )
        return password2

    class Meta:
        model = User
        fields = ('username', 'first_name')

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(label=u'帐号')
    password = forms.CharField(label=u'密码', widget=forms.PasswordInput)


class StoryForm(forms.ModelForm):
    title = forms.CharField(label=u'标题')
    content = forms.CharField(label=u'简介', widget=forms.Textarea)

    def save(self, user, commit=True):
        story = super(StoryForm, self).save(commit=False)
        story.created_by = user
        story.save()
        node = StoryNode(
            story=story,
            title='',
            content=self.cleaned_data['content'],
            parent=None,
            created_by=user)
        node.save()
        story.root = node
        story.save()
        return story

    class Meta:
        model = Story
        fields = ('title',)


class NodeForm(forms.ModelForm):
    title = forms.CharField(label=u'章节名')
    content = forms.CharField(label=u'内容', widget=forms.Textarea)

    def save(self, story, parent, user, commit=True):
        node = super(NodeForm, self).save(commit=False)
        node.created_by = user
        node.story = story
        node.parent = parent
        if commit:
            node.save()
        return node

    class Meta:
        model = StoryNode
        fields = ('title', 'content')

story/views.py
# coding: utf-8
from collections import defaultdict
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, REDIRECT_FIELD_NAME
from .models import Story, StoryNode
from .forms import LoginForm, RegisterForm, StoryForm, NodeForm


def index(request):
    stories = Story.objects.all()
    return render(request, 'story/index.html', {'stories': stories})


@login_required
def createstory(request):
    if request.method == 'POST':
        form = StoryForm(request.POST)
        if form.is_valid():
            story = form.save(request.user)
            return redirect('story:createnode', id=story.root_id)
    else:
        form = StoryForm()
    return render(request, 'story/createstory.html', {'form': form})


@login_required
def createnode(request, id):
    id = int(id)
    parent = StoryNode.objects.get(pk=id)
    story = parent.story
    if request.method == 'POST':
        form = NodeForm(request.POST)
        if form.is_valid():
            node = form.save(story, parent, request.user)
            return redirect('story:node', id=node.id)
    else:
        form = NodeForm()
    return render(request, 'story/createnode.html', {'story': story, 'parent': parent, 'form': form})


def node(request, id):
    node = StoryNode.objects.get(pk=int(id))
    return render(request, 'story/node.html', {'node': node})


def story(request, id):
    story = Story.objects.get(pk=int(id))
    candidates = StoryNode.objects\
        .filter(story=story)\
        .values('id',
                'parent_id',
                'created_by_id',
                'stars',
                'created_at'
                )

    children = defaultdict(list)
    for c in candidates:
        children[c['parent_id']].append(c)

    def sort_key(node):
        return (node['created_by_id'] != story.created_by_id, node['created_at'])

    rawnodes = []
    cs = children[story.root_id]
    while cs:
        cs.sort(key=sort_key)
        node = cs[0]
        rawnodes.append(node)
        cs = children[node['id']]

    nodes = StoryNode.objects.filter(id__in=[n['id'] for n in rawnodes])
    for n in nodes:
        n.count = len(children[n.parent_id]) - 1
    return render(request, 'story/story.html', {'story': story, 'nodes': nodes})


def nodelist(request, parentid, id=None):
    parent = StoryNode.objects.get(pk=int(parentid))
    nodes = StoryNode.objects.filter(parent_id=parent.id)
    return render(request, 'story/nodelist.html', {'nodes': nodes, 'parent': parent, 'id': id})


def login(request):
    error = []
    redirect_to = request.GET.get(REDIRECT_FIELD_NAME, '')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = data['username']
            password = data['password']
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                auth_login(request, user)
                return redirect(redirect_to or 'index')
            else:
                error.append('Please input the correct password')
        else:
            error.append('Please input both username and password')
    else:
        form = LoginForm()
    return render(request, 'story/login.html', {
        'form': form,
        'redirect_to': redirect_to,
        'redirect_name': REDIRECT_FIELD_NAME
    })


def register(request):
    redirect_to = request.GET.get(REDIRECT_FIELD_NAME, '')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'])
            auth_login(request, user)
            return redirect(redirect_to or 'index')
    else:
        form = RegisterForm()
    return render(request, 'story/register.html', {'form': form})

story/templates/story/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>
<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
  <meta name="description" content="Home">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <title>{% block title %}{% endblock %}</title>

  <!-- Set render engine for 360 browser -->
  <meta name="renderer" content="webkit">

  <!-- No Baidu Siteapp-->
  <meta http-equiv="Cache-Control" content="no-siteapp"/>

  <link rel="icon" type="image/png" href="i/favicon.png">

  <!-- Add to homescreen -->
  <link rel="manifest" href="manifest.json">

  <!-- Fallback to homescreen for Chrome <39 on Android -->
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="application-name" content="Web Starter Kit">
  <link rel="icon" sizes="192x192" href="i/touch/chrome-touch-icon-192x192.png">

  <!-- Add to homescreen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title"
        content="写故事">
  <link rel="apple-touch-icon" href="i/touch/apple-touch-icon.png">

  <!-- Tile icon for Win8 (144x144 + tile color) -->
  <meta name="msapplication-TileImage"
        content="i/touch/ms-touch-icon-144x144-precomposed.png">
  <meta name="msapplication-TileColor" content="#0e90d2">

    {% bootstrap_css %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block extra_head %}{% endblock %}
</head>

<body>
{% block content %}
{% endblock %}
{% if not 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
{% block extra_script %}{% endblock %}
<script type="text/javascript">
//iOS Web APP中点击链接跳转到Safari 浏览器新标签页的问题 devework.com
//stanislav.it/how-to-prevent-ios-standalone-mode-web-apps-from-opening-links-in-safari
if(("standalone" in window.navigator) && window.navigator.standalone){
var noddy, remotes = false;
document.addEventListener('click', function(event) {
noddy = event.target;
while(noddy.nodeName !== "A" && noddy.nodeName !== "HTML") {
noddy = noddy.parentNode;
}
if('href' in noddy && noddy.href.indexOf('http') !== -1 && (noddy.href.indexOf(document.location.host) !== -1 || remotes))
{
event.preventDefault();
document.location.href = noddy.href;
}
},false);
}
</script>
</body>

</html>

story/templates/story/createnode.html
{% extends 'story/base.html' %}
{% load bootstrap3 %}
{% load bootstrap_tags %}

{% block title %}create{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button onclick="window.location='{% url "story:nodelist" parentid=parent.id %}';return false;" class="btn btn-default glyphicon glyphicon-chevron-left"></button></li>
            <li style="list-style:none;margin:0;padding:0">
上一章: {% if parent.title %}<b><a href="{{parent.get_absolute_url}}">{{parent.title}}</a></b>{%else%}无{%endif%}
            </li>
            <li style="list-style:none;margin:0;padding:0"><button type="submit" class="btn btn-default glyphicon glyphicon-ok"></button></li>
        </ul>
    </div>
</div>
{{form|as_bootstrap}}
</form>
{% endblock %}

story/templates/story/createstory.html
{% extends 'story/base.html' %}
{% load bootstrap3 %}
{% load bootstrap_tags %}

{% block title %}create{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button class="btn btn-default glyphicon glyphicon-chevron-left" onclick="window.location='{% url "index"%}';return false;"></button></li>
            <li style="list-style:none;margin:0;padding:0"><b>新的故事</b></li>
            <li style="list-style:none;margin:0;padding:0"><button type="submit" class="btn btn-default glyphicon glyphicon-ok"></button></li>
        </ul>
    </div>
</div>
{{form|as_bootstrap}}
</form>
{% endblock %}

story/templates/story/index.html
{% extends 'story/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0;width:10%;"></li>
            <li style="list-style:none;margin:0;padding:0"><b>故事列表</b></li>
            <li style="list-style:none;margin:0;padding:0;"><button class="btn btn-default glyphicon glyphicon-plus" onclick="window.location='{% url "story:createstory" %}'"></button></li>
        </ul>
    </div>
</div>
<div class="list-group">
    {% for story in stories %}
    <a href="{{story.get_absolute_url}}" class="list-group-item">
        <span class="badge">★ {{story.stars|default:0}}</span>
        <span class="badge">作者: {{story.created_by.first_name}}</span>
        <h4 class="list-group-item-heading">{{story.title}}</h4>
        <p class="list-group-item-text">{{story.root.content}}</p>
    </a>
    {% endfor %}
</div>
{% endblock %}

story/templates/story/login.html
{% extends 'story/base.html' %}
{% load bootstrap3 %}
{% load bootstrap_tags %}

{% block title %}登录{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button onclick="window.location='{% url "index" %}'" class="btn btn-default glyphicon glyphicon-chevron-left"></button></li>
            <li style="list-style:none;margin:0;padding:0"><b>登录</b></li>
            <li style="list-style:none;margin:0;padding:0"><button onclick="window.location='{% url "story:register" %}?{{redirect_name}}={{redirect_to}}'" class="btn btn-default">注册</button></li>
        </ul>
    </div>
</div>
<form method="POST">
    {% csrf_token %}
    {{form|as_bootstrap}}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">登录</button>
    </div>
</form>
{% endblock %}

story/templates/story/node.html
{% extends 'story/base.html' %}
{% block title %}node{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button class="btn btn-default glyphicon glyphicon-chevron-left" onclick="window.location='{% url "story:story" id=node.story_id %}'"></button></li>
            <li style="list-style:none;margin:0;padding:0"><b>{{node.title}}</b></li>
            <li style="list-style:none;margin:0;padding:0">
                <button type="submit" class="btn btn-default glyphicon glyphicon-arrow-down" onclick="window.location='{% url "story:nodelist" parentid=node.id %}'"></button>
                <!--<button type="submit" class="btn btn-default glyphicon glyphicon-plus" onclick="window.location='{% url "story:createnode" id=node.id %}'"></button>-->
                <button type="submit" class="btn btn-default glyphicon glyphicon-list" onclick="window.location='{% url "story:nodelist" parentid=node.parent_id id=node.id %}'"></button>
            </li>
        </ul>
    </div>
</div>
<p>作者：{{node.created_by}}</p>
<pre>{{node.content}}</pre>
{% endblock %}

story/templates/story/nodelist.html
{% extends 'story/base.html' %}
{% block title %}nodelist{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button type="button" onclick="window.location='{% if id %}{% url "story:node" id=id %}{% else %}{% url "index" %}{% endif %}'" class="btn btn-default glyphicon glyphicon-menu-left"></button></li>
            <li style="list-style:none;margin:0;padding:0"><b>平行章节<b/></li>
            <li style="list-style:none;margin:0;padding:0;width:10%;">
                <button type="button" onclick="window.location='{% url "story:createnode" id=parent.id %}'" class="btn btn-default glyphicon glyphicon-plus"></button>
            </li>
        </ul>
    </div>
</div>
<div class="list-group">
    <div class="list-group-item">上一章：{% if parent.title %}<b><a href="{{parent.get_absolute_url}}">{{parent.title}}</a></b>{%else%}无{%endif%}</div>
    {% for node in nodes %}
    <a href="{% url 'story:node' id=node.id %}" class="list-group-item">
        <span class="badge">★ {{node.stars|default:0}}</span>
        <span class="badge">作者: {{node.created_by.first_name}}</span>
        {{node.title}}
    </a>
    {% endfor %}
</div>
{% endblock %}

story/templates/story/register.html
{% extends 'story/base.html' %}
{% load bootstrap3 %}
{% load bootstrap_tags %}

{% block title %}注册{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button onclick="window.location='{% url "index" %}'" class="btn btn-default glyphicon glyphicon-chevron-left"></button></li>
            <li style="list-style:none;margin:0;padding:0"><b>注册</b></li>
            <li style="list-style:none;margin:0;padding:0"><button onclick="window.location='{% url "story:login" %}'"class="btn btn-default">登录</button></li>
        </ul>
    </div>
</div>
<form method="POST">
    {% csrf_token %}
    {{form|as_bootstrap}}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">注册</button>
    </div>
</form>
{% endblock %}

story/templates/story/story.html
{% extends 'story/base.html' %}
{% block title %}nodelist{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <ul style="display:flex;flex-direction:row;padding:0; margin:0;justify-content:space-between;align-items:center;">
            <li style="list-style:none;margin:0;padding:0"><button type="button" onclick="window.location='{% url "index" %}'" class="btn btn-default glyphicon glyphicon-menu-left"></button></li>
            <li style="list-style:none;margin:0;padding:0"><b>{{story.title}}<b/></li>
            <li style="list-style:none;margin:0;padding:0;width:10%;">
            </li>
        </ul>
    </div>
</div>
<div class="list-group">
    {% for node in nodes %}
    <a href="{% url 'story:node' id=node.id %}" class="list-group-item">
        <span class="badge">★ {{node.stars|default:0}}</span>
        <span class="badge">作者: {{node.created_by.first_name}}</span>
        {% if node.count %}
        <span class="badge">平行: {{node.count}}</span>
        {% endif %}
        {{node.title}}
    </a>
    {% endfor %}
</div>
{% endblock %}